### ISSUE TITLE
[Bug] OldWorldMenu

### ISSUE THREAD

**Issue by QueenUlyana** [RaderRMT/Timeless#4] opened 2023-07-01 11:48 UTC
**It does not allow you to create a world with a chosen seed, it creates worlds with random seeds. How did you miss that?**
@RaderRMT

**Comment by RaderRMT** [comment] 2023-07-01 11:55
> How did you miss that?

no particular reason. I'm a human, and humans forget stuff

i'll fix it asap

**Comment by RaderRMT** [comment] 2023-07-01 11:57
also, duplicate of #3

**Comment by RaderRMT** [comment] 2023-07-03 17:48
fixed. please update

**Closed as completed by RaderRMT** 2023-07-03 17:48 UTC
